/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
using namespace std;

/* Header for class jung_sy_firstndk_MainActivity */

#ifndef _Included_jung_sy_firstndk_MainActivity
#define _Included_jung_sy_firstndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jung_sy_firstndk_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jung_sy_firstndk_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
